apiVersion: v1              # Version de l'API Kubernetes (comme une version de Windows)
kind: Secret                # Type d'objet : un Secret (pour les mots de passe)
metadata:
  name: mysql-secret        # Le nom du Secret (on l'utilisera dans d'autres fichiers)
type: Opaque                # Type générique de Secret
stringData:                 # Les données (Kubernetes les encodera en base64 automatiquement)
  MYSQL_ROOT_PASSWORD: rootpass    # Mot de passe root MySQL
  MYSQL_DATABASE: tododb           # Nom de la base de données







